stages:
  - prerequisite
  - tests
  - security_check
  - build

# deps_install:
#   stage: prerequisite
#   image: node:19-alpine
#   cache:
#     paths:
#       - node_modules
#   script:
#     - yarn install

npm-audit:
  image: node:19-alpine
  stage: security_check
  # dependencies:
  #   - deps_install
  script:
    - yarn audit || exit 1
  after_script:
    - echo $EXIT_CODE
    - echo $CI_JOB_STATUS
    - echo $SLACK_HOOK_URL
    - echo $SLACK_CHANNEL
    - echo $SLACK_HOOK_TEXT
    - >
      if [[ $CI_JOB_STATUS != 'success' ]]; then
        echo 'Security check failed'

        if $SLACK_HOOK_URL; then
          wget -O- --post-data="{\"channel\": \"$SLACK_CHANNEL\", \"username\": \"webhookbot\", \"text\": \"$SLACK_HOOK_TEXT\", \"icon_emoji\": \":warning:\"}" --header='Content-Type:application/json' $SLACK_HOOK_URL
        else
          echo "SLACK_HOOK_URL variable is not present, skipping Slack notification"
        fi
      else
        echo "Security check passed"
      fi