variables:
  SLACK_PAYLOAD: "payload={\"channel\": \"$SLACK_CHANNEL\", \"username\": \"webhookbot\", \"text\": \"$SLACK_HOOK_TEXT\", \"icon_emoji\": \":warning:\"}"

stages:
  - prerequisite
  - tests
  - security_check
  - build

deps_install:
  stage: prerequisite
  image: node:19-alpine
  cache:
    paths:
      - node_modules
  script:
    - yarn install

npm_audit:
  image: node:19-alpine
  stage: security_check
  dependencies:
    - deps_install
  script:
    - yarn audit || exit 1

security_slack_notification:
  stage: security_check
  needs: ["npm_audit"]
  when: on_failure
  image: curlimages/curl
  rules:
    - if: $SLACK_HOOK_URL != null
  before_script:
    - echo $SLACK_HOOK_URL
    - echo $SLACK_CHANNEL
    - echo $SLACK_HOOK_TEXT
    - echo $SLACK_PAYLOAD
  script: curl -X POST --data-urlencode "$SLACK_PAYLOAD" "$SLACK_HOOK_URL"