stages:
  - prerequisite
  - tests
  - security_check
  - build

deps_install:
  stage: prerequisite
  image: node:19-alpine
  cache:
    paths:
      - node_modules
  script:
    - yarn install

npm-audit:
  image: node:19-alpine
  stage: security_check
  rules:
    - if: $SLACK_HOOK_URL == null
      when: never # don't run the job in this case
    - when: on_success  # run per usual in all other cases
  script:
    - yarn audit