stages:
  - prerequisite
  - tests
  - security_check
  - build

deps_install:
  stage: prerequisite
  image: node:19-alpine
  cache:
    paths:
      - node_modules
  script:
    - yarn install

npm-audit:
  image: node:19-alpine
  stage: security_check
  script:
    - yarn audit || exit 1
  after_script:
    - >
      if [ $CI_JOB_STATUS != 'success' ] && [ -n "$SLACK_HOOK_URL" ]; then
        echo 'Security check failed'
        echo $SLACK_CHANNEL
        echo $SLACK_HOOK_TEXT
        echo $SLACK_HOOK_URL
        curl -X POST --data-urlencode "payload={\"channel\": \"$SLACK_CHANNEL\", \"username\": \"webhookbot\", \"text\": \"$SLACK_HOOK_TEXT\", \"icon_emoji\": \":warning:\"}" $SLACK_HOOK_URL
      fi