// CORE
export const SET_SELECT_LOCALE_ACTION = 'SET_SELECT_LOCALE_ACTION';
export const SET_ONBOARDING_FINISHED = 'SET_ONBOARDING_FINISHED';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const RESET_LOCATION = 'RESET_LOCATION';
export const SET_NETWORK_STATUS = 'SET_NETWORK_STATUS';
export const SHOW_HEADER = 'SHOW_HEADER';
export const HIDE_HEADER = 'HIDE_HEADER';

export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';

// LANGUAGE
export const SET_LOCALE = 'SET_LOCALE';

// FILTERS
export const SET_SITE_TYPE_FILTER = 'SET_SITE_TYPE_FILTER';
export const SET_REGION_FILTER = 'SET_REGION_FILTER';
export const SET_HIGHWAY_FILTER = 'SET_HIGHWAY_FILTER';

// LISTING
export const TOGGLE_LISTING_VIEW = 'TOGGLE_LISTING_VIEW';
export const FILTER_LISTING = 'FILTER_LISTING';
export const TOGGLE_LISTING_FILTER_STATE = 'TOGGLE_LISTING_FILTER_STATE';
export const INCREMENT_LISTING_PAGE = 'INCREMENT_LISTING_PAGE';
export const ADD_LISTING = 'ADD_LISTING';

// GEOLOCATION MAP

export const ADD_GM_LISTING = 'ADD_GM_LISTING';
export const UPDATED_GM_LISTING = 'UPDATED_GM_LISTING';


// SEARCH
export const SEARCH_SITES = 'SEARCH_SITES';
export const SEARCH_IN_PROGRESS = 'SEARCH_IN_PROGRESS';
export const RESET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const INCREMENT_SEARCH_PAGE = 'INCREMENT_SEARCH_PAGE';

// REGION
export const RESET_REGION = 'RESET_REGION';

// SITE TYPE
export const RESET_SITE_TYPE = 'RESET_SITE_TYPE';

// BOOKMARKS
export const SET_FAVORITES = 'SET_FAVORITES';
