// CORE
export const SET_SELECT_LOCALE_ACTION = 'SET_SELECT_LOCALE_ACTION';
export const SET_ONBOARDING_FINISHED = 'SET_ONBOARDING_FINISHED';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const RESET_LOCATION = 'RESET_LOCATION';
export const SET_NETWORK_STATUS = 'SET_NETWORK_STATUS';
export const SHOW_HEADER = 'SHOW_HEADER';
export const HIDE_HEADER = 'HIDE_HEADER';

// LANGUAGE
export const SET_LOCALE = 'SET_LOCALE';

// FILTERS
export const RESET_FILTERS = 'RESET_FILTERS';
export const SET_HIGHWAY_FILTERS = 'SET_HIGHWAY_FILTERS';
export const SET_REGION_FILTERS = 'SET_REGION_FILTERS';
export const SET_NEAR_ME_FILTERS = 'SET_NEAR_ME_FILTERS';
export const SET_MY_SITES_FILTERS = 'SET_MY_SITES_FILTERS';
export const SET_HIGHWAY_SELECTION = 'SET_HIGHWAY_SELECTION';
export const SET_SITES_TYPE_FILTER_VISIBILITY = 'SET_SITES_TYPE_FILTER_VISIBILITY';
export const SET_SITES_TYPE_FILTER = 'SET_SITES_TYPE_FILTER';
export const TOGGLE_MY_SITES_STATE = 'TOGGLE_MY_SITES_STATE';

// LISTING
export const TOGGLE_LISTING_VIEW = 'TOGGLE_LISTING_VIEW';
export const FILTER_LISTING = 'FILTER_LISTING';
export const TOGGLE_LISTING_FILTER_STATE = 'TOGGLE_LISTING_FILTER_STATE';
export const INCREMENT_LISTING_PAGE = 'INCREMENT_LISTING_PAGE';
export const ADD_LISTING = 'ADD_LISTING';

// GEOLOCATION MAP

export const ADD_GM_LISTING = 'ADD_GM_LISTING';
export const UPDATED_GM_LISTING = 'UPDATED_GM_LISTING';


// SEARCH
export const SEARCH_SITES = 'SEARCH_SITES';
export const SEARCH_IN_PROGRESS = 'SEARCH_IN_PROGRESS';
export const RESET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const INCREMENT_SEARCH_PAGE = 'INCREMENT_SEARCH_PAGE';

// REGION
export const RESET_REGION = 'RESET_REGION';

// SITE TYPE
export const RESET_SITE_TYPE = 'RESET_SITE_TYPE';
