// CORE
export const SET_SELECT_LOCALE_ACTION = 'SET_SELECT_LOCALE_ACTION';
export const SET_ONBOARDING_FINISHED = 'SET_ONBOARDING_FINISHED';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const RESET_LOCATION = 'RESET_LOCATION';
export const SET_NETWORK_STATUS = 'SET_NETWORK_STATUS';
export const SHOW_HEADER = 'SHOW_HEADER';
export const HIDE_HEADER = 'HIDE_HEADER';
export const SET_CURRENT_SCREEN_NAME = 'SET_CURRENT_SCREEN_NAME';

export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const SHOW_SEARCH = 'SHOW_SEARCH';
export const HIDE_SEARCH = 'HIDE_SEARCH';

export const GET_USER_LOCATION_BEGIN = 'GET_USER_LOCATION_BEGIN';
export const GET_USER_LOCATION_SUCCESS = 'GET_USER_LOCATION_SUCCESS';
export const GET_USER_LOCATION_FAILURE = 'GET_USER_LOCATION_FAILURE';

export const SET_SITE_DISTANCE = 'SET_SITE_DISTANCE';

// LANGUAGE
export const SET_LOCALE = 'SET_LOCALE';

// FILTERS
export const SET_SITE_TYPE_FILTER = 'SET_SITE_TYPE_FILTER';
export const SET_REGION_FILTER = 'SET_REGION_FILTER';
export const SET_HIGHWAY_FILTER = 'SET_HIGHWAY_FILTER';

// LISTING
export const FILTER_LISTING = 'FILTER_LISTING';
export const ADD_LISTING = 'ADD_LISTING';

// BOOKMARKS
export const SET_FAVORITES = 'SET_FAVORITES';
