name: "iOS Build"

on:
  workflow_dispatch:
    inputs:
      publish:
        required: false
        type: boolean
        description: "Publish to Appcenter"
    secrets:
      IOS_P12_BASE64:
        required: true
      IOS_MOBILEPROVISION_BASE64:
        required: true
      IOS_TEAM_ID:
        required: true
      IOS_CERTIFICATE_PASSWORD:
        required: true
      APPCENTER_TOKEN_IOS:
        required: true

jobs:
  build-ios:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: "Use Node.js 18"
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: "Install Node modules"
        run: yarn install

      - name: "[iOS] Restore Pods cache"
        uses: actions/cache@v3
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: "[iOS] Install pod dependencies"
        run: cd ios && pod install && cd ..

      - name: "[iOS] Build iOS (Release)"
        uses: yukiarrr/ios-build-action@v1.11.2
        with:
          project-path: ios/yukon.xcodeproj
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILEPROVISION_BASE64 }}
          code-signing-identity: "Apple Distribution"
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          team-id: ${{ secrets.IOS_TEAM_ID }}
          workspace-path: ios/yukon.xcworkspace
          output-path: "yukon.ipa"

      - name: "[iOS] Upload build"
        uses: actions/upload-artifact@v3
        with:
          name: "yukon.ipa"
          path: "yukon.ipa"

  publish-to-appcenter:
    if: ${{ inputs.publish == true }}
    runs-on: ubuntu-latest
    needs: build-ios

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: yukon.ipa
          path: "ios/"

      - name: "[iOS] Set up JDK 1.8"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: "[iOS] Upload artifact to App Center"
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: "Government-of-Yukon/Sights-and-Sites-iOS"
          token: ${{secrets.APPCENTER_TOKEN_IOS}}
          group: Collaborators
          file: "ios/yukon.ipa"
          notifyTesters: true
          debug: false
