name: Pull Request into `v2`

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "v2"

jobs:
  #First job
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install Node modules
        run: yarn install --frozen-lockfile

  # Second Job
  android:
    needs: install-dependencies
    uses: ./.github/workflows/build-android.yml
    with:
      environment: release
      publish: true
    secrets: inherit

  # Third Job
  ios:
    needs: install-dependencies
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit