name: "Notify Slack"

on: workflow_dispatch

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "🚀 New release",
              "attachments": [
                {
                  "pretext": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": false,
                      "value": "Completed"
                    },
                    {
                      "title": "",
                      "short": false,
                      "value": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    },
                    {
                      "title": "Created by",
                      "short": true,
                      "value": "Robert Ngo ${{ inputType }} - ${{ lastCommit }} - ${{ lastUser }} - ${{ lastUser2 }} "
                    },
                    {
                      "title": "Created on",
                      "short": true,
                      "value": "March 28"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
